unformatted_string = """'1': 'Swimming pool', '2': 'Parking', '3': 'Restaurant', '4': 'Pet friendly', '5': 'Room service', '6': 'Meeting/Banquet facilities', '7': 'Bar', '8': '24-hour front desk', '9': 'Tennis court', '10': 'Sauna', '11': 'Fitness center', '12': 'Golf course (within 2 miles)', '13': 'Newspapers', '14': 'Garden', '15': 'Terrace', '16': 'Non-smoking rooms', '17': 'Airport shuttle', '19': 'Fishing', '20': 'Business center', '21': 'Babysitting/Child services', '22': 'Laundry', '23': 'Dry cleaning', '24': 'Continental breakfast', '25': 'Facilities for disabled guests', '26': 'Skiing', '27': 'Hair/Beauty salon', '28': 'Family rooms', '29': 'Game room', '30': 'Casino', '41': 'VIP room facilities', '43': 'Breakfast in the room', '44': 'Ironing service', '45': 'Honeymoon suite', '46': 'Free parking', '47': 'Internet', '48': 'Elevator', '49': 'Express check-in/out', '50': 'Solarium', '51': 'Safe', '52': 'Valet parking', '53': 'Currency exchange', '54': 'Spa', '55': 'Massage', '56': 'Playground', '57': 'Pool table', '58': 'Ping-pong', '59': 'Karaoke', '60': 'Gift shop', '61': 'Windsurfing', '62': 'Darts', '63': 'Hot tub/Jacuzzi', '64': 'Soundproof rooms', '65': 'Bicycle rental (additional charge)', '66': 'Library', '67': 'Shoeshine', '69': 'Canoeing', '70': 'Hiking', '71': 'Chapel/Shrine', '72': 'BBQ facilities', '73': 'Packed lunches', '75': 'Car rental', '76': 'Cycling', '77': 'Bowling', '78': 'Tour desk', '79': 'Turkish/Steam Bath', '80': 'Heating', '81': 'Fax/Photocopying', '82': 'Diving', '86': 'Horseback riding', '87': 'Racquetball', '88': 'Designer Hotel', '89': 'Ticket service', '90': 'Snorkeling', '91': 'Baggage storage', '92': 'Shops on site', '96': 'WiFi', '97': 'Mini golf', '98': 'Gay Friendly', '99': 'Ski storage', '100': 'Ski school', '101': 'Hypoallergenic room available', '102': 'Breakfast Buffet', '103': 'Indoor pool', '104': 'Outdoor pool', '107': 'Free WiFi', '108': 'Smoke-free property', '109': 'Air conditioning', '110': 'Designated smoking area', '111': 'ATM on site', '114': 'Private beach area', '115': 'Restaurant', '116': 'Buffet', '117': 'Snack bar', '118': 'Sun deck', '119': 'Outdoor pool (year-round)', '120': 'Outdoor pool (seasonal)', '121': 'Indoor pool (year-round)', '122': 'Indoor pool (seasonal)', '123': 'Bikes available (free)', '124': 'Concierge', '125': 'Entertainment staff', '126': 'Nightclub/DJ', '127': 'Private check-in/out', '128': 'Shuttle service (free)', '129': 'Shuttle service (additional charge)', '130': 'Ski rental on site', '131': 'Ski pass vendor', '132': 'Ski-in, ski-out access', '133': 'Special diet meals (on request)', '134': 'Suit press', '135': 'Vending machine (drinks)', '136': 'Vending machine (snacks)', '137': 'Water sports facilities on site', '138': 'Hot spring bath', '139': 'Airport shuttle (free)', '140': 'Airport shuttle (additional charge)', '141': 'Shared kitchen', '142': 'Lockers', '143': 'Shared lounge/TV area', '144': "Kids' club", '145': 'Convenience store on site', '146': 'Beachfront', '147': 'Evening entertainment', '148': 'Water park', '149': 'Adults only', '150': 'Detached - Entire property', '151': 'Semi-detached', '152': 'Privately-owned apartment', '153': 'Ground floor (private access)', '154': 'Ground floor (shared access)', '155': 'Upper floor - elevator', '156': 'Upper floor - stairs', '157': 'Wheelchair accessible', '158': 'Daily housekeeping', '159': 'Grocery deliveries', '160': 'Parking on site', '161': 'Private Parking', '162': 'Misc parking', '163': 'WiFi in all areas', '164': 'Paid WiFi', '165': 'Michelin-star Dining', '166': 'Open-air bath', '167': 'Public Bath', '168': 'Waterslide', '169': 'Swimming pool toys', '170': 'Board games/Puzzles', '171': 'Books, DVDs & music for kids', '172': 'Indoor play area', '173': 'Outdoor play equipment for kids', '174': 'Baby safety gates', '175': "Kids' TV channels", '176': "Kids' meals", '177': 'Kid-friendly buffet', '178': 'Sofa Bed', '179': 'Secure parking', '180': 'Street parking', '181': 'Parking garage', '182': 'Electric vehicle charging station', '183': 'Public transit tickets', '184': 'Accessible parking', '185': 'Wheelchair accessible', '186': 'Toilet with grab rails', '187': 'Raised toilet', '188': 'Lowered sink', '189': 'Bathroom emergency cord', '192': 'Rooftop pool', '193': 'Infinity pool', '194': 'Pool with view', '195': 'Heated pool', '196': 'Saltwater pool', '197': 'Plunge pool', '198': 'Pool/Beach towels', '199': 'Pool bar', '200': 'Shallow end', '201': 'Pool cover', '203': 'Wine/Champagne', '204': 'Bottle of water', '205': 'Fruit', '206': 'Chocolate/Cookies', '207': 'Tickets to shows/attractions', '209': 'Airport pickup', '210': 'Airport drop-off', '211': 'Visual aids (Braille)', '212': 'Visual aids (tactile signs)', '213': 'Auditory guidance', '214': 'Strollers', '215': 'Tennis equipment', '216': 'Badminton equipment', '217': 'Pet basket', '218': 'Pet bowls', '219': 'Coffee house on site', '220': 'Beach chairs/Loungers', '221': 'Beach umbrellas', '222': 'Outdoor furniture', '223': 'Fenced pool', '224': 'Picnic area', '225': 'Outdoor fireplace', '226': 'Beauty services', '227': 'Facial treatments', '228': 'Waxing services', '229': 'Makeup services', '230': 'Hair treatments', '231': 'Manicure', '232': 'Pedicure', '233': 'Haircut', '234': 'Hair coloring', '235': 'Hairstyling', '236': 'Body treatments', '237': 'Body scrub', '238': 'Body wrap', '239': 'Light therapy', '240': 'Spa facilities', '241': 'Steam room', '242': 'Spa lounge/Relaxation area', '243': 'Foot bath', '244': 'Spa/Wellness packages', '245': 'Back massage', '246': 'Neck massage', '247': 'Foot massage', '248': "Couples' massage", '249': 'Head massage', '250': 'Hand massage', '251': 'Full-body massage', '252': 'Massage chair', '253': 'Fitness', '254': 'Yoga classes', '255': 'Fitness classes', '256': 'Personal trainer', '257': 'Locker rooms', '258': "Kids' pool", '301': 'Swimming pool', '302': 'Beach', '303': 'Special baths', '304': 'Shuttle service', '305': 'Breakfast options', '306': 'Game drives', '307': 'The Big Five', '308': 'Walking Safari', '309': 'Bush Dinner', '310': 'Game Drives', '311': 'The Big Five', '312': 'Walking Safari', '313': 'Bush Dinner', '400': 'Temporary art galleries', '401': 'Bar crawls', '402': 'Stand-up comedy', '403': 'Movie nights', '404': 'Walking tours', '405': 'Bike tours', '406': 'Themed dinners', '407': 'Happy hour', '408': 'Tour or class about local culture', '409': 'Cooking class', '410': 'Live music/Performance', '411': 'Live sports events (broadcast)', '412': 'Archery', '413': 'Aerobics', '414': 'Bingo', '415': 'Downhill Skiing', '418': '24-hour security', '419': 'Key access', '420': 'Key card access', '421': 'Security alarm', '422': 'Smoke alarms', '423': 'CCTV in common areas', '424': 'CCTV outside property', '425': 'Fire extinguishers', '426': 'Bicycle parking', '427': 'Telephone', '428': 'Postal service', '429': 'Laundry room', '430': 'Ski shuttle', '431': 'Bath/Hot spring', '432': 'Private bath', '433': 'Swimming pool', '434': 'No single-use plastics', '435': 'Have you removed (or never offered) all single-use plastic miniature shampoo, conditioner, and body wash bottles?', '436': 'Guests have the option to reuse towels', '437': 'Carbon monoxide detector', '438': 'Carbon monoxide sources', '439': 'Have you removed (or never offered) all plastic straws?', '440': 'Have you removed (or never offered) all plastic cups?', '441': 'Have you removed (or never offered) all plastic water bottles?', '442': 'Have you removed (or never offered) all plastic bottles for other drinks?', '443': 'Have you removed (or never offered) all plastic cutlery and tableware?', '444': 'Key card or motion-controlled electricity for guests', '445': 'Guests can opt out of daily cleaning service', '446': 'Water cooler/dispenser', '447': 'Bicycle rental', '448': 'Have you removed (or never offered) all plastic stirrers?', '449': 'Use of cleaning chemicals that are effective against coronavirus', '450': 'Linens, towels, and laundry washed in accordance with local authority guidelines', '451': 'Guest accommodation disinfected between stays', '452': 'Guest accommodation sealed after cleaning', '453': 'Physical distancing in dining areas', '454': 'Food can be delivered to guest accommodation', '455': 'Staff follow all safety protocols as directed by local authorities', '456': 'Shared stationery (e.g. printed menus, magazines, pens, paper) removed', '457': 'Hand sanitizer in guest accommodation and common areas', '458': 'Process in place to check health of guests', '459': 'First aid kits available', '460': 'Contactless check-in/out', '461': 'Cashless payment available', '462': 'Physical distancing rules followed', '463': 'Mobile app for room service', '464': 'Screens or physical barriers between staff and guests in appropriate areas', '465': 'Invoice provided', '466': 'Property cleaned by professional cleaning companies', '467': 'All plates, cutlery, glasses, and other tableware sanitized', '468': 'Guests have the option to cancel any cleaning services for their accommodation during their stay', '470': 'Passport/ID info collected online before you arrive', '471': 'Check-in kiosk in the lobby', '472': 'Lockbox key collection at the property', '473': 'Lockbox key collection near the property', '474': 'Digital key access', '484': 'Breakfast to-go containers', '485': 'Delivered food covered securely', '486': 'Access to healthcare professionals', '487': 'Thermometers for guests provided by property', '488': 'Face masks for guests available', '489': "Wild (non-domesticated) animals aren't displayed or interacted with while kept at the property, nor are they harvested, consumed, or sold.", '490': 'Recycling bins are available to guests and waste is recycled', '491': 'At least 80% of food is sourced from your region', '492': 'At least 80% of lighting uses energy-efficient LED bulbs', '493': 'Only using water-efficient toilets (e.g. low-flow toilets, dual flush toilets)', '494': 'Only using water-efficient showers (e.g smart showers, low-flow shower heads)', '495': 'All windows are double-glazed', '496': 'Food waste policy in place that includes education, food waste prevention, reduction, recycling, and disposal', '497': 'A percentage of revenue is invested back into community or sustainability projects', '498': 'Compensate for at least 10% of total annual carbon emissions by purchasing certified carbon offsets', '499': 'Tours and activities organized by local guides and businesses', '500': 'Vegetarian menu options available', '501': 'Vegan menu options available', '502': 'Green spaces like (rooftop) gardens at the property', '503': 'At least 80% of provided food is organic', '504': '100% renewable electricity used throughout the property', '505': 'Local artists are offered a platform to display their talents', '506': 'Provide guests with info about local ecosystems, history, culture, and visitor etiquette', '507': '100% renewable energy is used throughout the property', '508': 'Local artists are offered a platform to display their talents', '509': 'Provide guests with information regarding local ecosystems, heritage and culture, as well as visitor etiquette', '510': 'Provide guests with information regarding local ecosystems, heritage and culture, as well as visitor etiquette', '511': 'Indoor fireplace', '512': 'Breakfast to go', '513': 'Breakfast to go', '514': 'Breakfast to go', 'other': ''"""

formatted_string = ""
for i in range(len(unformatted_string)):
    if unformatted_string[i-2:i+2] == "', '":
        formatted_string += "\n"
    else:
        formatted_string += unformatted_string[i]

print(formatted_string)

indices_filters = {
'1': 'Swimming pool',
'2': 'Parking',
'3': 'Restaurant',
'4': 'Pet friendly',
'5': 'Room service',
'6': 'Meeting/Banquet facilities',
'7': 'Bar',
'8': '24-hour front desk',
'9': 'Tennis court',
'10': 'Sauna',
'11': 'Fitness center',
'12': 'Golf course (within 2 miles)',
'13': 'Newspapers',
'14': 'Garden',
'15': 'Terrace',
'16': 'Non-smoking rooms',
'17': 'Airport shuttle',
'19': 'Fishing',
'20': 'Business center',
'21': 'Babysitting/Child services',
'22': 'Laundry',
'23': 'Dry cleaning',
'24': 'Continental breakfast',
'25': 'Facilities for disabled guests',
'26': 'Skiing',
'27': 'Hair/Beauty salon',
'28': 'Family rooms',
'29': 'Game room',
'30': 'Casino',
'41': 'VIP room facilities',
'43': 'Breakfast in the room',
'44': 'Ironing service',
'45': 'Honeymoon suite',
'46': 'Free parking',
'47': 'Internet',
'48': 'Elevator',
'49': 'Express check-in/out',
'50': 'Solarium',
'51': 'Safe',
'52': 'Valet parking',
'53': 'Currency exchange',
'54': 'Spa',
'55': 'Massage',
'56': 'Playground',
'57': 'Pool table',
'58': 'Ping-pong',
'59': 'Karaoke',
'60': 'Gift shop',
'61': 'Windsurfing',
'62': 'Darts',
'63': 'Hot tub/Jacuzzi',
'64': 'Soundproof rooms',
'65': 'Bicycle rental (additional charge)',
'66': 'Library',
'67': 'Shoeshine',
'69': 'Canoeing',
'70': 'Hiking',
'71': 'Chapel/Shrine',
'72': 'BBQ facilities',
'73': 'Packed lunches',
'75': 'Car rental',
'76': 'Cycling',
'77': 'Bowling',
'78': 'Tour desk',
'79': 'Turkish/Steam Bath',
'80': 'Heating',
'81': 'Fax/Photocopying',
'82': 'Diving',
'86': 'Horseback riding',
'87': 'Racquetball',
'88': 'Designer Hotel',
'89': 'Ticket service',
'90': 'Snorkeling',
'91': 'Baggage storage',
'92': 'Shops on site',
'96': 'WiFi',
'97': 'Mini golf',
'98': 'Gay Friendly',
'99': 'Ski storage',
'100': 'Ski school',
'101': 'Hypoallergenic room available',
'102': 'Breakfast Buffet',
'103': 'Indoor pool',
'104': 'Outdoor pool',
'107': 'Free WiFi',
'108': 'Smoke-free property',
'109': 'Air conditioning',
'110': 'Designated smoking area',
'111': 'ATM on site',
'114': 'Private beach area',
'115': 'Restaurant',
'116': 'Buffet',
'117': 'Snack bar',
'118': 'Sun deck',
'119': 'Outdoor pool (year-round)',
'120': 'Outdoor pool (seasonal)',
'121': 'Indoor pool (year-round)',
'122': 'Indoor pool (seasonal)',
'123': 'Bikes available (free)',
'124': 'Concierge',
'125': 'Entertainment staff',
'126': 'Nightclub/DJ',
'127': 'Private check-in/out',
'128': 'Shuttle service (free)',
'129': 'Shuttle service (additional charge)',
'130': 'Ski rental on site',
'131': 'Ski pass vendor',
'132': 'Ski-in, ski-out access',
'133': 'Special diet meals (on request)',
'134': 'Suit press',
'135': 'Vending machine (drinks)',
'136': 'Vending machine (snacks)',
'137': 'Water sports facilities on site',
'138': 'Hot spring bath',
'139': 'Airport shuttle (free)',
'140': 'Airport shuttle (additional charge)',
'141': 'Shared kitchen',
'142': 'Lockers',
'143': 'Shared lounge/TV area',
'144': "Kids' club", '145': 'Convenience store on site',
'146': 'Beachfront',
'147': 'Evening entertainment',
'148': 'Water park',
'149': 'Adults only',
'150': 'Detached - Entire property',
'151': 'Semi-detached',
'152': 'Privately-owned apartment',
'153': 'Ground floor (private access)',
'154': 'Ground floor (shared access)',
'155': 'Upper floor - elevator',
'156': 'Upper floor - stairs',
'157': 'Wheelchair accessible',
'158': 'Daily housekeeping',
'159': 'Grocery deliveries',
'160': 'Parking on site',
'161': 'Private Parking',
'162': 'Misc parking',
'163': 'WiFi in all areas',
'164': 'Paid WiFi',
'165': 'Michelin-star Dining',
'166': 'Open-air bath',
'167': 'Public Bath',
'168': 'Waterslide',
'169': 'Swimming pool toys',
'170': 'Board games/Puzzles',
'171': 'Books, DVDs & music for kids',
'172': 'Indoor play area',
'173': 'Outdoor play equipment for kids',
'174': 'Baby safety gates',
'175': "Kids' TV channels", '176': "Kids' meals", '177': 'Kid-friendly buffet',
'178': 'Sofa Bed',
'179': 'Secure parking',
'180': 'Street parking',
'181': 'Parking garage',
'182': 'Electric vehicle charging station',
'183': 'Public transit tickets',
'184': 'Accessible parking',
'185': 'Wheelchair accessible',
'186': 'Toilet with grab rails',
'187': 'Raised toilet',
'188': 'Lowered sink',
'189': 'Bathroom emergency cord',
'192': 'Rooftop pool',
'193': 'Infinity pool',
'194': 'Pool with view',
'195': 'Heated pool',
'196': 'Saltwater pool',
'197': 'Plunge pool',
'198': 'Pool/Beach towels',
'199': 'Pool bar',
'200': 'Shallow end',
'201': 'Pool cover',
'203': 'Wine/Champagne',
'204': 'Bottle of water',
'205': 'Fruit',
'206': 'Chocolate/Cookies',
'207': 'Tickets to shows/attractions',
'209': 'Airport pickup',
'210': 'Airport drop-off',
'211': 'Visual aids (Braille)',
'212': 'Visual aids (tactile signs)',
'213': 'Auditory guidance',
'214': 'Strollers',
'215': 'Tennis equipment',
'216': 'Badminton equipment',
'217': 'Pet basket',
'218': 'Pet bowls',
'219': 'Coffee house on site',
'220': 'Beach chairs/Loungers',
'221': 'Beach umbrellas',
'222': 'Outdoor furniture',
'223': 'Fenced pool',
'224': 'Picnic area',
'225': 'Outdoor fireplace',
'226': 'Beauty services',
'227': 'Facial treatments',
'228': 'Waxing services',
'229': 'Makeup services',
'230': 'Hair treatments',
'231': 'Manicure',
'232': 'Pedicure',
'233': 'Haircut',
'234': 'Hair coloring',
'235': 'Hairstyling',
'236': 'Body treatments',
'237': 'Body scrub',
'238': 'Body wrap',
'239': 'Light therapy',
'240': 'Spa facilities',
'241': 'Steam room',
'242': 'Spa lounge/Relaxation area',
'243': 'Foot bath',
'244': 'Spa/Wellness packages',
'245': 'Back massage',
'246': 'Neck massage',
'247': 'Foot massage',
'248': "Couples' massage", '249': 'Head massage',
'250': 'Hand massage',
'251': 'Full-body massage',
'252': 'Massage chair',
'253': 'Fitness',
'254': 'Yoga classes',
'255': 'Fitness classes',
'256': 'Personal trainer',
'257': 'Locker rooms',
'258': "Kids' pool", '301': 'Swimming pool',
'302': 'Beach',
'303': 'Special baths',
'304': 'Shuttle service',
'305': 'Breakfast options',
'306': 'Game drives',
'307': 'The Big Five',
'308': 'Walking Safari',
'309': 'Bush Dinner',
'310': 'Game Drives',
'311': 'The Big Five',
'312': 'Walking Safari',
'313': 'Bush Dinner',
'400': 'Temporary art galleries',
'401': 'Bar crawls',
'402': 'Stand-up comedy',
'403': 'Movie nights',
'404': 'Walking tours',
'405': 'Bike tours',
'406': 'Themed dinners',
'407': 'Happy hour',
'408': 'Tour or class about local culture',
'409': 'Cooking class',
'410': 'Live music/Performance',
'411': 'Live sports events (broadcast)',
'412': 'Archery',
'413': 'Aerobics',
'414': 'Bingo',
'415': 'Downhill Skiing',
'418': '24-hour security',
'419': 'Key access',
'420': 'Key card access',
'421': 'Security alarm',
'422': 'Smoke alarms',
'423': 'CCTV in common areas',
'424': 'CCTV outside property',
'425': 'Fire extinguishers',
'426': 'Bicycle parking',
'427': 'Telephone',
'428': 'Postal service',
'429': 'Laundry room',
'430': 'Ski shuttle',
'431': 'Bath/Hot spring',
'432': 'Private bath',
'433': 'Swimming pool',
'434': 'No single-use plastics',
'435': 'Have you removed (or never offered) all single-use plastic miniature shampoo, conditioner, and body wash bottles?',
'436': 'Guests have the option to reuse towels',
'437': 'Carbon monoxide detector',
'438': 'Carbon monoxide sources',
'439': 'Have you removed (or never offered) all plastic straws?',
'440': 'Have you removed (or never offered) all plastic cups?',
'441': 'Have you removed (or never offered) all plastic water bottles?',
'442': 'Have you removed (or never offered) all plastic bottles for other drinks?',
'443': 'Have you removed (or never offered) all plastic cutlery and tableware?',
'444': 'Key card or motion-controlled electricity for guests',
'445': 'Guests can opt out of daily cleaning service',
'446': 'Water cooler/dispenser',
'447': 'Bicycle rental',
'448': 'Have you removed (or never offered) all plastic stirrers?',
'449': 'Use of cleaning chemicals that are effective against coronavirus',
'450': 'Linens, towels, and laundry washed in accordance with local authority guidelines',
'451': 'Guest accommodation disinfected between stays',
'452': 'Guest accommodation sealed after cleaning',
'453': 'Physical distancing in dining areas',
'454': 'Food can be delivered to guest accommodation',
'455': 'Staff follow all safety protocols as directed by local authorities',
'456': 'Shared stationery (e.g. printed menus, magazines, pens, paper) removed',
'457': 'Hand sanitizer in guest accommodation and common areas',
'458': 'Process in place to check health of guests',
'459': 'First aid kits available',
'460': 'Contactless check-in/out',
'461': 'Cashless payment available',
'462': 'Physical distancing rules followed',
'463': 'Mobile app for room service',
'464': 'Screens or physical barriers between staff and guests in appropriate areas',
'465': 'Invoice provided',
'466': 'Property cleaned by professional cleaning companies',
'467': 'All plates, cutlery, glasses, and other tableware sanitized',
'468': 'Guests have the option to cancel any cleaning services for their accommodation during their stay',
'470': 'Passport/ID info collected online before you arrive',
'471': 'Check-in kiosk in the lobby',
'472': 'Lockbox key collection at the property',
'473': 'Lockbox key collection near the property',
'474': 'Digital key access',
'484': 'Breakfast to-go containers',
'485': 'Delivered food covered securely',
'486': 'Access to healthcare professionals',
'487': 'Thermometers for guests provided by property',
'488': 'Face masks for guests available',
'489': "Wild (non-domesticated) animals aren't displayed or interacted with while kept at the property, nor are they harvested, consumed, or sold.", '490': 'Recycling bins are available to guests and waste is recycled',
'491': 'At least 80% of food is sourced from your region',
'492': 'At least 80% of lighting uses energy-efficient LED bulbs',
'493': 'Only using water-efficient toilets (e.g. low-flow toilets, dual flush toilets)',
'494': 'Only using water-efficient showers (e.g smart showers, low-flow shower heads)',
'495': 'All windows are double-glazed',
'496': 'Food waste policy in place that includes education, food waste prevention, reduction, recycling, and disposal',
'497': 'A percentage of revenue is invested back into community or sustainability projects',
'498': 'Compensate for at least 10% of total annual carbon emissions by purchasing certified carbon offsets',
'499': 'Tours and activities organized by local guides and businesses',
'500': 'Vegetarian menu options available',
'501': 'Vegan menu options available',
'502': 'Green spaces like (rooftop) gardens at the property',
'503': 'At least 80% of provided food is organic',
'504': '100% renewable electricity used throughout the property',
'505': 'Local artists are offered a platform to display their talents',
'506': 'Provide guests with info about local ecosystems, history, culture, and visitor etiquette',
'507': '100% renewable energy is used throughout the property',
'508': 'Local artists are offered a platform to display their talents',
'509': 'Provide guests with information regarding local ecosystems, heritage and culture, as well as visitor etiquette',
'510': 'Provide guests with information regarding local ecosystems, heritage and culture, as well as visitor etiquette',
'511': 'Indoor fireplace',
'512': 'Breakfast to go',
'513': 'Breakfast to go',
'514': 'Breakfast to go',
'other': ''
}
filters_indices = {v: k for k, v in indices_filters.items()}

unformatted_string = str(filters_indices)
formatted_string = ""
for i in range(len(unformatted_string)):
    if unformatted_string[i-2:i+2] == "', '":
        formatted_string += "\n"
    else:
        formatted_string += unformatted_string[i]

print(formatted_string)